apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ include "spring-petclinic-kubernetes.name" . }}
    chart: {{ include "spring-petclinic-kubernetes.chart" . }}
    spring-boot: "true"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "spring-petclinic-kubernetes.name" . }}
    release: {{ .Release.Name }}
