{{- $fullName := include "spring-petclinic-ingress-rules.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ include "spring-petclinic-ingress-rules.name" . }}
    chart: {{ include "spring-petclinic-ingress-rules.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: /api/owner/?(.*)
          backend:
            serviceName: owners-service
            servicePort: 8080
        - path: /api/visit/?(.*)
          backend:
            serviceName: visits-service
            servicePort: 8080
        - path: /api/customer/?(.*)
          backend:
            serviceName: customers-service
            servicePort: 8080
        - path: /api/vet/?(.*)
          backend:
            serviceName: vets-service
            servicePort: 8080
        - path: /?(.*)
          backend:
            serviceName: frontend-service
            servicePort: 8080
  {{- end }}
